{{- if and .Values.global.enabled_helm .Values.provider.enabled }}
{{- with .Values.provider }}
apiVersion: pkg.crossplane.io/{{ $.Values.crossplaneApiVersion | default "v2" }}
kind: Provider
metadata:
  name: {{ .metadata.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    {{- range $key, $value := .metadata.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}

  {{- if .metadata.labels }}
  labels:
    {{- range $key, $value := .metadata.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v2.0.0
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/{{ $.Values.crossplaneApiVersion | default "v2" }}
    kind: DeploymentRuntimeConfig
    name: {{ $.Values.deploymentRuntimeConfig.metadata.name }}
{{- end }}
{{- end }}
