apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.example.org
spec:
  group: example.org
  names:
    kind: XBucket
    plural: xbuckets
    shortNames:
      - xb
  claimNames:
    kind: BucketClaim
    plural: bucketclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                bucketName:
                  type: string
                region:
                  type: string
                acl:
                  type: string
                versioning:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                tags:
                  type: object
                  additionalProperties:
                    type: string
              required:
                - bucketName
                - region