{{- if and .Values.global.enabled_aws_upbound .Values.provider.enabled }}
{{- with .Values.provider }}
apiVersion: pkg.crossplane.io/{{ $.Values.crossplaneApiVersion | default "v2" }}
kind: Provider
metadata:
  name: upbound-provider-family-aws
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    {{- range $key, $value := .metadata.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}

  {{- if .metadata.labels }}
  labels:
    {{- range $key, $value := .metadata.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- $reg := $.Values.provider.package.registry | default "xpkg.crossplane.io/upbound" }}
  {{- $ver := $.Values.provider.package.version | default "v2.0.0" }}
  {{- $override := index $.Values.provider.package "override" | default "" }}
  {{- if $override }}
  package: {{ $override | quote }}
  {{- else }}
  package: {{ printf "%s/provider-family-aws:%s" $reg $ver }}
  {{- end }}


{{- end }}
{{- end }}
